#!/usr/bin/env python

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import sys, re

try:
    from collections.abc import Sequence
except:
    # python2 version
    from collections import Sequence


from ask import *


def ask_help(short=False):
    print('ask.py (version {:}) -- query a stdin response.'.format(ask_version))
    print('Usage: ask.py [options] question message')
    if short:
        return
    print('Options:')
    print('  -?,-h,--help            Prints this text.')
    print('  -a,--accepted=answers   Comma seperated accepted answers.')
    print('  -d,--default=default    Use default answer if empty response.')
    print('  -i,--input=file         Read input from file.')
    print('  -n,--tries=tries        The number of tries before using default.')
    print('  -o,--output=file        Send output to file.')
    print('  -p,--previous=answer    The previous answer (maintain state).')
    print('  -q,--quiet              Set verbosity to 0.')
    print('  -v,-vv,-vvv,-vvvv       Set to errors, normal, info, or debug.')
    print('  --                      Terminates argument parsing.')
    print('Arguments:')
    print('  question                The question to ask.')
    print('  message                 The rejected response message.')
    print('Notes:')
    print('  * A dash("-") can be used to represent an empty argument.')
    print('  * The "accepted" argument is optional only if embedded as a ')
    print('    comma seperated encapsulated("[", "]") list in the question.')
    print('  * Accepted answers may include a capitalize letter to offer ')
    print('    single character responses.  Otherwise answers will match ')
    print('    only the first n characters of input.')
    print('  * Verbosity is set using "-v" and "-q", multiple v\'s may be ')
    print('    used with a single dash("-"), where "-q"=silent, ')
    print('    "-v"=errors, "-vv"=normal and "-vvv"=debug.')


def main():
    from sys import argv
    args, kwargs = list(argv[1:]), { }
    argi, argc = 0, len(args)
    showhelp, exitvalue = False, 0
    inp, out, err = sys.stdin, sys.stdout, sys.stderr
    def getargs(arg=None, t=str):
        nonlocal args, argi, argc
        result = None
        if type(arg) is str and '=' in arg:
            result = arg[arg.index('=') + 1:]
        if argi + 1 < argc:
            result = args.pop(argi + 1)
            argc -= 1
        if type(result) is str:
            result = None if result in ("-", "") else t(result)
        return result
    while argi < argc and exitvalue == 0:
        arg, argarg = args[argi], None
        if arg.startswith("-"):
            if arg == "--":
                args = args[:argi]
                break
            if len(arg) > 1:
                args.pop(argi)
                argc -= 1
                if '=' in arg:
                    i = arg.index('=') 
                    arg, argarg = arg[:i], arg[i+1:]
                if arg in ("-a", "--accepted"):
                    kwargs["accepted"] = getargs(argarg)
                elif arg in ("-d", "--default"):
                    kwargs["default"] = getargs(argarg)
                elif arg in ("-i", "--output"):
                    inp = getargs(argarg)
                    if inp is None:
                        inp = sys.stdin
                elif arg in ("-o", "--output"):
                    out = getargs(argarg)
                    if out is None:
                        out = sys.stdout
                elif arg in ("-p", "--previous"):
                    kwargs["previous"] = getargs(argarg)
                elif arg in("-q", "--quiet"):
                    kwargs["verbosity"] = 0
                elif arg in ("-n", "--tries"):
                    kwargs["tries"] = getargs(argarg, int)
                elif arg.startswith("-v") and all(c == 'v' for c in arg[1:]):
                    kwargs["verbosity"] = len(arg) - 1
                elif arg in ("-?", "-h", "--help"):
                    showhelp = True
                else:
                    print("[Error] bad switch or option: {:}".format(arg),
                          file=err)
                    showhelp = True
                    exitvalue = -1
                continue
            args[argi] = None
        argi += 1
    if argc > 2:
        print("[Error] extra arguments: {:}".format(', '.join(args[2:])),
              file=err)
        showhelp = True
        exitvalue = -1
    if argc == 0 or showhelp:
        ask_help()
    elif exitvalue == 0:
        if kwargs["verbosity"] >= 4:
            print("args: {:}".format(', '.join(repr(a) for a in args)), file=err)
            print("kwargs: {:}"
                  .format(', '.join("{:}: {:}"
                                    .format(repr(k), repr(a))
                                            for (k, a) in kwargs.items())),
                  file=err)
        try:
            answer = ask(*args, **kwargs)
            print(answer, file=out)
        except ValueError as ve:
            exitvalue = -1
            print("[Error] {:}".format(str(ve)), file=err)
            ask_help(True)
    exit(exitvalue)


if __name__ == '__main__':
    main()
